// List of animals for random generation
const ANIMALS = [
  '🐶 Anjing',
  '🐱 Kucing',
  '🐭 Tikus',
  '🐹 Hamster',
  '🐰 Kelinci',
  '🦊 Rubah',
  '🐻 Beruang',
  '🐼 Panda',
  '🐨 Koala',
  '🐯 Harimau',
  '🦁 Singa',
  '🐮 Sapi',
  '🐷 Babi',
  '🐸 Katak',
  '🐵 Monyet',
  '🐔 Ayam',
  '🦅 Elang',
  '🦆 Bebek',
  '🦉 Burung Hantu',
  '🦢 Angsa',
  '🦜 Beo',
  '🦚 Merak',
  '🦑 Gurita',
  '🐙 Gurita Besar',
  '🦐 Udang',
  '🐟 Ikan',
  '🐠 Ikan Gold',
  '🐡 Ikan Buntal',
  '🦈 Hiu',
  '🐢 Kura-kura',
  '🐍 Ular',
  '🦎 Kadal',
  '🦖 T-Rex',
  '🦕 Dinosaurus',
  '🐌 Siput',
  '🦋 Kupu-kupu',
  '🐛 Belatung',
  '🐝 Lebah',
  '🪲 Kumbang',
  '🦗 Jangkrik',
  '🕷️ Laba-laba',
  '🦂 Kalajengking',
  '🐾 Jejak Kaki',
  '🦓 Zebra',
  '🐘 Gajah',
  '🦛 Kuda Nil',
  '🦏 Badak',
  '🐪 Unta',
  '🐫 Unta Dua Punuk',
  '🦒 Jerapah',
  '🦘 Kanguru',
  '🐃 Banteng',
  '🐂 Sapi Jantan',
  '🐄 Sapi Betina',
  '🐎 Kuda',
  '🐖 Babi Hutan',
  '🐏 Domba Jantan',
  '🐑 Domba Betina',
  '🦌 Rusa',
  '🦍 Gorila',
  '🦧 Orang Utan',
  '🐒 Monyet Kecil',
  '🦥 Sloth',
  '🦘 Kangaroo',
  '🐩 Pudel',
  '🦮 Anjing Pemandu',
  '🐈 Kucing',
  '🐓 Ayam Jantan',
  '🦃 Kalkun',
  '🦚 Merak',
  '🦜 Burung Beo',
  '🦢 Angsa',
  '🦗 Jangkrik',
  '🕷️ Laba-laba',
  '🦂 Kalajengking',
  '🐢 Penyu',
  '🐍 Ular',
  '🦎 Biawak',
]

export function getRandomAnimal(): string {
  const animal = ANIMALS[Math.floor(Math.random() * ANIMALS.length)]
  return getAnimalEmoji(animal)
}

export function getAnimalEmoji(animal: string): string {
  return animal.split(' ')[0]
}

export function getAnimalName(animal: string): string {
  return animal.split(' ').slice(1).join(' ')
}
